name: iOS build (xcodebuild)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: AiCareersApp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve SwiftPM dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project "$(ls -1 *.xcodeproj | head -n1)"

      - name: Build (Debug, iPhone Simulator)
        run: |
          NAME=$(ls -1 *.xcodeproj | head -n1 | sed 's/\.xcodeproj$//')
          xcodebuild \
            -project "$NAME.xcodeproj" \
            -scheme "$NAME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
