name: iOS build (xcodebuild)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: YOUR_FOLDER_HERE

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve SwiftPM dependencies
        run: |
          if ls -1 *.xcworkspace >/dev/null 2>&1; then
            xcodebuild -resolvePackageDependencies -workspace "$(ls -1 *.xcworkspace | head -n1)"
          else
            xcodebuild -resolvePackageDependencies -project "$(ls -1 *.xcodeproj | head -n1)"
          fi

      - name: Build (Debug, iPhone Simulator)
        run: |
          NAME=$(ls -1 *.xcworkspace *.xcodeproj 2>/dev/null | head -n1 | sed 's/\.\(xcworkspace\|xcodeproj\)$//')
          if ls -1 *.xcworkspace >/dev/null 2>&1; then
            xcodebuild \
              -workspace "$NAME.xcworkspace" \
              -scheme "$NAME" \
              -sdk iphonesimulator \
              -configuration Debug \
              -destination 'platform=iOS Simulator,name=iPhone 15' \
              build
          else
            xcodebuild \
              -project "$NAME.xcodeproj" \
              -scheme "$NAME" \
              -sdk iphonesimulator \
              -configuration Debug \
              -destination 'platform=iOS Simulator,name=iPhone 15' \
              build
          fi
